# Generated by Django 4.0.5 on 2022-07-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_dislikes_post_likes_userprofile_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/comics/'),
        ),
    ]
