# Generated by Django 4.1 on 2023-01-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_post_favorites_userprofile_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='profileFavorites', to='social.post'),
        ),
    ]
